# Generated by Django 5.0.2 on 2024-03-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationfile',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='notification.notification'),
            preserve_default=False,
        ),
    ]
