# Generated by Django 5.0.2 on 2024-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_exhibitionfile_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionfile',
            name='download_path',
            field=models.ImageField(default=1, upload_to='exhibition_down/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
