# Generated by Django 5.0.2 on 2024-03-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_exhibitionfile_download_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='exhibition_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='exhibition_content',
            field=models.CharField(max_length=1000),
        ),
    ]
