# Generated by Django 5.0.2 on 2024-02-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_groupnumber',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_status',
        ),
        migrations.AddField(
            model_name='reply',
            name='group_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_private_status',
            field=models.BooleanField(choices=[(True, '비밀 댓글'), (False, '일반 대글')], default=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_depth',
            field=models.BigIntegerField(default=1),
        ),
    ]
