# Generated by Django 5.0.2 on 2024-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0003_alter_reply_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_private_status',
            field=models.BooleanField(choices=[(True, '비밀 댓글'), (False, '일반 대글')], default=False),
        ),
    ]
