# Generated by Django 5.0.2 on 2024-02-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_budget', models.BigIntegerField(default=0)),
                ('travel_destination', models.TextField()),
                ('travel_date', models.TextField()),
                ('travel_hotel_reservation', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_travel',
            },
        ),
    ]
