# Generated by Django 5.0.2 on 2024-03-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_phone',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='member_school_email',
            field=models.CharField(default='<EMAIL>', max_length=50),
        ),
    ]
