# Generated by Django 5.0.2 on 2024-03-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_member_phone_member_member_school_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
