# Generated by Django 5.0.2 on 2024-03-14 15:16

import django.views.generic.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_member_is_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLoginView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=0, help_text='Visit count')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django.views.generic.base.View),
        ),
        migrations.AddField(
            model_name='member',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='Visit count'),
        ),
    ]
