# Generated by Django 5.0.2 on 2024-03-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_memberloginview_member_visit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='visit_count',
        ),
    ]
