# Generated by Django 5.0.2 on 2024-03-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_remove_member_visit_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberLoginView',
        ),
    ]
